In [45]:
import pandas as pd

In [46]:
df=pd.read_csv('cybersecurity_intrusion_data.csv')

In [47]:
df.head()

,session_id,network_packet_size,protocol_type,login_attempts,session_duration,encryption_used,ip_reputation_score,failed_logins,browser_type,unusual_time_access,attack_detected
0,SID_00001,599,TCP,4,492.983263,DES,0.606818,1,Edge,0,1
1,SID_00002,472,TCP,3,1557.996461,DES,0.301569,0,Firefox,0,0
2,SID_00003,629,TCP,3,75.044262,DES,0.739164,2,Chrome,0,1
3,SID_00004,804,UDP,4,601.248835,DES,0.123267,0,Unknown,0,1
4,SID_00005,453,TCP,5,532.540888,AES,0.054874,1,Firefox,0,0

In [48]:
df.dtypes

session_id              object
network_packet_size      int64
protocol_type           object
login_attempts           int64
session_duration       float64
encryption_used         object
ip_reputation_score    float64
failed_logins            int64
browser_type            object
unusual_time_access      int64
attack_detected          int64
dtype: object


The file cybersecurity_intrusion_data.csv contains **9,537 **records of network activity with a unique session ID (session_id) and 10 features used for intrusion detection. It includes attributes like packet size, protocol type, login attempts, session duration, encryption type, IP reputation score,failed logins, browser type, unusual time access, and a binary attack detection label (attack_detected).

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

### Data Preparation

In [50]:
df["encryption_used"] = df["encryption_used"].fillna("Unknown")
category_columns = ["protocol_type", "encryption_used", "browser_type"]

In [51]:
# Import the RobustScaler class from sklearn.preprocessing
from sklearn.preprocessing import RobustScaler

In [52]:
# List of columns to be scaled
encode_to_columns = ['network_packet_size', 'login_attempts', 'session_duration','ip_reputation_score', 'failed_logins']

In [53]:

# Initialize the RobustScaler
scaler = RobustScaler()

In [54]:

# Apply the scaler to the specified columns and transform the data
# Scaling is done to normalize the data, making it less sensitive to outliers
df[encode_to_columns] = scaler.fit_transform(df[encode_to_columns])

In [55]:
# Drop the specified columns from the DataFrame
# Dropping unnecessary columns to reduce dimensionality and focus on relevant features
df = df.drop(["session_id", "protocol_type", "encryption_used"], axis=1)

In [56]:
# Convert categorical variable 'browser_type' into dummy/indicator variables
# Encoding categorical variables to numerical format for machine learning algorithms
# drop_first=True removes the first category 
df = pd.get_dummies(df, columns=["browser_type"], drop_first=True)

In [57]:
df.head()

,network_packet_size,login_attempts,session_duration,ip_reputation_score,failed_logins,unusual_time_access,attack_detected,browser_type_Edge,browser_type_Firefox,browser_type_Safari,browser_type_Unknown
0,0.370370,0.0,-0.072466,1.117038,0.0,0,1,True,False,False,False
1,-0.100000,-0.5,1.146883,-0.050524,-1.0,0,0,False,True,False,False
2,0.481481,-0.5,-0.550971,1.623256,1.0,0,1,False,False,False,False
3,1.129630,0.0,0.051488,-0.732520,-1.0,0,1,False,False,False,True
4,-0.170370,0.5,-0.027176,-0.994121,0.0,0,0,False,True,False,False

### SVM

In [58]:
X = df.drop(["attack_detected"], axis=1)
y = df["attack_detected"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
model = SVC()

In [60]:
 model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [61]:
acc = accuracy_score(y_test, y_pred)

In [62]:
acc

0.890461215932914

Activity 1: We learned about different kernels. Try different kernels and evaluate the performance

Activity 2: We learned about different evaluation metrics. Generate the different evaluation metrics to evaluate SVM performance with different kernels